### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by liamwh** [jeremychone/rust-genai#23]
Some types are undocumented, for example, `genai::resolver::AuthData`. 

Might I suggest enabling the following in `Cargo.toml` and addressing all lint warnings?

```toml
[lints.rust]
missing_docs = "warn"
```

And enabling the following may also help maintain code quality:
```toml
[lints.clippy]
pedantic = "deny"
nursery = "deny"
```
